export const CHAT_TYPES = {
  TOGGLE_CHAT: 'TOGGLE_CHAT',
  ADD_MESSAGE_ERROR: 'ADD_MESSAGE_ERROR',
  ADD_MESSAGE_SUCCESS: 'ADD_MESSAGE_SUCCESS',
  ADD_MESSAGE: 'ADD_MESSAGE',
  ADD_MESSAGE_WITH_LINKS: 'ADD_MESSAGE_WITH_LINKS',
  REMOVE_LINKS: 'REMOVE_LINKS',
  SET_TYPE: "SET_TYPE"
}
