export const CHAT_TYPES = {
  TOGGLE_CHAT: 'TOGGLE_CHAT',
  ADD_MESSAGE: 'ADD_MESSAGE',
  ADD_MESSAGE_WITH_LINKS: 'ADD_MESSAGE_WITH_LINKS',
  REMOVE_LINKS: 'REMOVE_LINKS',
  SET_TYPE: 'SET_TYPE',
  START_LOADING: 'START_LOADING',
  END_LOADING: 'END_LOADING',
  DEFAULT_BANNERS: 'DEFAULT_BANNERS'
}
